#!/bin/sh

set -ex

# Frontend
if [ "$1" = "pwa" ]; then
    # Install native dependencies
    apt update
    apt install -y default-jdk

    # Generate dependencies
    make depend

    # Build
    make build/cljs-kitchen-sink

    exit 0
fi
